# SHOPIFY
POST http://localhost:3000/api/2021-02/order.create
Content-Type: application/json
Accept: application/json
x-shopify-shop-domain: kids-living.myshopify.com

{
  "id": 3829589967023,
  "admin_graphql_api_id": "gid://shopify/Order/3829589967023",
  "app_id": 580111,
  "browser_ip": "196.61.101.174",
  "buyer_accepts_marketing": true,
  "cancel_reason": null,
  "cancelled_at": null,
  "cart_token": "dbcd02106ed1aff6ca6abea6dba0a042",
  "checkout_id": 20897556922543,
  "checkout_token": "30b3ef65422b85cbdc5ffc80f22b8957",
  "client_details": {
    "accept_language": "en-us",
    "browser_height": 828,
    "browser_ip": "196.61.101.174",
    "browser_width": 414,
    "session_hash": null,
    "user_agent": "Mozilla/5.0 (iPhone; CPU iPhone OS 14_4_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 Instagram 187.0.0.32.120 (iPhone11,8; iOS 14_4_2; en_ZA; en-ZA; scale=2.00; 828x1792; 289678855)"
  },
  "closed_at": null,
  "confirmed": true,
  "contact_email": "esce.cohen@gmail.com",
  "created_at": "2021-05-15T11:58:23+02:00",
  "currency": "ZAR",
  "current_subtotal_price": "3449.00",
  "current_subtotal_price_set": {
    "shop_money": {
      "amount": "3449.00",
      "currency_code": "ZAR"
    },
    "presentment_money": {
      "amount": "3449.00",
      "currency_code": "ZAR"
    }
  },
  "current_total_discounts": "0.00",
  "current_total_discounts_set": {
    "shop_money": {
      "amount": "0.00",
      "currency_code": "ZAR"
    },
    "presentment_money": {
      "amount": "0.00",
      "currency_code": "ZAR"
    }
  },
  "current_total_duties_set": null,
  "current_total_price": "3534.00",
  "current_total_price_set": {
    "shop_money": {
      "amount": "3534.00",
      "currency_code": "ZAR"
    },
    "presentment_money": {
      "amount": "3534.00",
      "currency_code": "ZAR"
    }
  },
  "current_total_tax": "449.87",
  "current_total_tax_set": {
    "shop_money": {
      "amount": "449.87",
      "currency_code": "ZAR"
    },
    "presentment_money": {
      "amount": "449.87",
      "currency_code": "ZAR"
    }
  },
  "customer_locale": "en",
  "device_id": null,
  "discount_codes": [],
  "email": "esce.cohen@gmail.com",
  "financial_status": "paid",
  "fulfillment_status": null,
  "gateway": "Electronic Transfer (EFT)",
  "landing_site": "/",
  "landing_site_ref": null,
  "location_id": null,
  "name": "#13546",
  "note": "",
  "note_attributes": [],
  "number": 12546,
  "order_number": 13546,
  "order_status_url": "https://kidsliving.co.za/15673213/orders/b3ac200abe1d789e742a14256c18aac3/authenticate?key=b8d1bc3ff4219a77c0ad1a8c698bd927",
  "original_total_duties_set": null,
  "payment_gateway_names": [
    "Electronic Transfer (EFT)"
  ],
  "phone": null,
  "presentment_currency": "ZAR",
  "processed_at": "2021-05-15T11:58:21+02:00",
  "processing_method": "manual",
  "reference": null,
  "referring_site": "",
  "source_identifier": null,
  "source_name": "web",
  "source_url": null,
  "subtotal_price": "3449.00",
  "subtotal_price_set": {
    "shop_money": {
      "amount": "3449.00",
      "currency_code": "ZAR"
    },
    "presentment_money": {
      "amount": "3449.00",
      "currency_code": "ZAR"
    }
  },
  "tags": "",
  "tax_lines": [
    {
      "price": "449.87",
      "rate": 0.15,
      "title": "VAT",
      "price_set": {
        "shop_money": {
          "amount": "449.87",
          "currency_code": "ZAR"
        },
        "presentment_money": {
          "amount": "449.87",
          "currency_code": "ZAR"
        }
      }
    }
  ],
  "taxes_included": true,
  "test": false,
  "token": "b3ac200abe1d789e742a14256c18aac3",
  "total_discounts": "0.00",
  "total_discounts_set": {
    "shop_money": {
      "amount": "0.00",
      "currency_code": "ZAR"
    },
    "presentment_money": {
      "amount": "0.00",
      "currency_code": "ZAR"
    }
  },
  "total_line_items_price": "3449.00",
  "total_line_items_price_set": {
    "shop_money": {
      "amount": "3449.00",
      "currency_code": "ZAR"
    },
    "presentment_money": {
      "amount": "3449.00",
      "currency_code": "ZAR"
    }
  },
  "total_outstanding": "0.00",
  "total_price": "3534.00",
  "total_price_set": {
    "shop_money": {
      "amount": "3534.00",
      "currency_code": "ZAR"
    },
    "presentment_money": {
      "amount": "3534.00",
      "currency_code": "ZAR"
    }
  },
  "total_price_usd": "249.84",
  "total_shipping_price_set": {
    "shop_money": {
      "amount": "85.00",
      "currency_code": "ZAR"
    },
    "presentment_money": {
      "amount": "85.00",
      "currency_code": "ZAR"
    }
  },
  "total_tax": "449.87",
  "total_tax_set": {
    "shop_money": {
      "amount": "449.87",
      "currency_code": "ZAR"
    },
    "presentment_money": {
      "amount": "449.87",
      "currency_code": "ZAR"
    }
  },
  "total_tip_received": "0.00",
  "total_weight": 17000,
  "updated_at": "2021-05-17T17:06:58+02:00",
  "user_id": null,
  "billing_address": {
    "first_name": "Esce",
    "address1": "7 Mulvihal Road, Rondebosch",
    "phone": "072 601 3655",
    "city": "Cape town ",
    "zip": "7700",
    "province": "Western Cape",
    "country": "South Africa",
    "last_name": "Cohen",
    "address2": "Unit 3 ",
    "company": "",
    "latitude": -33.9655249,
    "longitude": 18.489506,
    "name": "Esce Cohen",
    "country_code": "ZA",
    "province_code": "WC"
  },
  "customer": {
    "id": 5194784899247,
    "email": "esce.cohen@gmail.com",
    "accepts_marketing": true,
    "created_at": "2021-05-08T15:30:05+02:00",
    "updated_at": "2021-05-15T11:58:23+02:00",
    "first_name": "Esce",
    "last_name": "Cohen",
    "orders_count": 1,
    "state": "enabled",
    "total_spent": "3534.00",
    "last_order_id": 3829589967023,
    "note": null,
    "verified_email": false,
    "multipass_identifier": null,
    "tax_exempt": false,
    "phone": null,
    "tags": "",
    "last_order_name": "#13546",
    "currency": "ZAR",
    "accepts_marketing_updated_at": "2021-05-08T15:30:05+02:00",
    "marketing_opt_in_level": "single_opt_in",
    "tax_exemptions": [],
    "admin_graphql_api_id": "gid://shopify/Customer/5194784899247",
    "default_address": {
      "id": 6393081331887,
      "customer_id": 5194784899247,
      "first_name": "Esce",
      "last_name": "Cohen",
      "company": "",
      "address1": "7 Mulvihal Road, Rondebosch",
      "address2": "Unit 3 ",
      "city": "Cape town",
      "province": "Western Cape",
      "country": "South Africa",
      "zip": "7700",
      "phone": "072 601 3655",
      "name": "Esce Cohen",
      "province_code": "WC",
      "country_code": "ZA",
      "country_name": "South Africa",
      "default": true
    }
  },
  "discount_applications": [],
  "fulfillments": [],
  "line_items": [
    {
      "id": 9913088901295,
      "admin_graphql_api_id": "gid://shopify/LineItem/9913088901295",
      "fulfillable_quantity": 1,
      "fulfillment_service": "manual",
      "fulfillment_status": null,
      "gift_card": false,
      "grams": 2000,
      "name": "Mattress Bamboopaedic 120 cm x 60 cm",
      "origin_location": {
        "id": 2030453063740,
        "country_code": "ZA",
        "province_code": "WC",
        "name": "Kids Living",
        "address1": "15 Hudson Street",
        "address2": "Greenpoint",
        "city": "Cape Town",
        "zip": "8001"
      },
      "price": "699.00",
      "price_set": {
        "shop_money": {
          "amount": "699.00",
          "currency_code": "ZAR"
        },
        "presentment_money": {
          "amount": "699.00",
          "currency_code": "ZAR"
        }
      },
      "product_exists": true,
      "product_id": 9969126994,
      "properties": [],
      "quantity": 1,
      "requires_shipping": true,
      "sku": "FMATTBAMB120X60",
      "taxable": true,
      "title": "Mattress Bamboopaedic 120 cm x 60 cm",
      "total_discount": "0.00",
      "total_discount_set": {
        "shop_money": {
          "amount": "0.00",
          "currency_code": "ZAR"
        },
        "presentment_money": {
          "amount": "0.00",
          "currency_code": "ZAR"
        }
      },
      "variant_id": 38492576338,
      "variant_inventory_management": "shopify",
      "variant_title": "",
      "vendor": "Snuggletime",
      "tax_lines": [
        {
          "price": "91.17",
          "price_set": {
            "shop_money": {
              "amount": "91.17",
              "currency_code": "ZAR"
            },
            "presentment_money": {
              "amount": "91.17",
              "currency_code": "ZAR"
            }
          },
          "rate": 0.15,
          "title": "VAT"
        }
      ],
      "duties": [],
      "discount_allocations": []
    },
    {
      "id": 9913088934063,
      "admin_graphql_api_id": "gid://shopify/LineItem/9913088934063",
      "fulfillable_quantity": 1,
      "fulfillment_service": "manual",
      "fulfillment_status": null,
      "gift_card": false,
      "grams": 15000,
      "name": "Kids River Cot Felix - Natural",
      "origin_location": {
        "id": 2030453063740,
        "country_code": "ZA",
        "province_code": "WC",
        "name": "Kids Living",
        "address1": "15 Hudson Street",
        "address2": "Greenpoint",
        "city": "Cape Town",
        "zip": "8001"
      },
      "price": "2750.00",
      "price_set": {
        "shop_money": {
          "amount": "2750.00",
          "currency_code": "ZAR"
        },
        "presentment_money": {
          "amount": "2750.00",
          "currency_code": "ZAR"
        }
      },
      "product_exists": true,
      "product_id": 10459748498,
      "properties": [
        {
          "name": "Pre-Order",
          "value": "Estimated Dispatch in  may container"
        }
      ],
      "quantity": 1,
      "requires_shipping": true,
      "sku": "KRCOTFELIXNATUR",
      "taxable": true,
      "title": "Kids River Cot Felix",
      "total_discount": "0.00",
      "total_discount_set": {
        "shop_money": {
          "amount": "0.00",
          "currency_code": "ZAR"
        },
        "presentment_money": {
          "amount": "0.00",
          "currency_code": "ZAR"
        }
      },
      "variant_id": 42248252114,
      "variant_inventory_management": "shopify",
      "variant_title": "Natural",
      "vendor": "Kids River",
      "tax_lines": [
        {
          "price": "358.70",
          "price_set": {
            "shop_money": {
              "amount": "358.70",
              "currency_code": "ZAR"
            },
            "presentment_money": {
              "amount": "358.70",
              "currency_code": "ZAR"
            }
          },
          "rate": 0.15,
          "title": "VAT"
        }
      ],
      "duties": [],
      "discount_allocations": []
    }
  ],
  "refunds": [],
  "shipping_address": {
    "first_name": "Esce",
    "address1": "7 Mulvihal Road, Rondebosch",
    "phone": "072 601 3655",
    "city": "Cape town ",
    "zip": "7700",
    "province": "Western Cape",
    "country": "South Africa",
    "last_name": "Cohen",
    "address2": "Unit 3 ",
    "company": "",
    "latitude": -33.9655249,
    "longitude": 18.489506,
    "name": "Esce Cohen",
    "country_code": "ZA",
    "province_code": "WC"
  },
  "shipping_lines": [
    {
      "id": 3223261806767,
      "carrier_identifier": "414127336c64f5eed2fa6b34fbc5a7e3",
      "code": "courier-door-to-door-delivery-economy",
      "delivery_category": null,
      "discounted_price": "85.00",
      "discounted_price_set": {
        "shop_money": {
          "amount": "85.00",
          "currency_code": "ZAR"
        },
        "presentment_money": {
          "amount": "85.00",
          "currency_code": "ZAR"
        }
      },
      "phone": null,
      "price": "85.00",
      "price_set": {
        "shop_money": {
          "amount": "85.00",
          "currency_code": "ZAR"
        },
        "presentment_money": {
          "amount": "85.00",
          "currency_code": "ZAR"
        }
      },
      "requested_fulfillment_service_id": null,
      "source": "uAfrica Shipping Rates",
      "title": "Courier Door to Door Delivery - Economy",
      "tax_lines": [],
      "discount_allocations": []
    }
  ]
}


###
# SHOPIFY create
POST https://kids-living.myshopify.com/admin/api/2021-01/graphql.json
Content-Type: application/graphql
X-Shopify-Access-Token: 7522f1ec2ce1989ac523647deae8d00b

# TODO quantities will be known from webhook - make use of it

{
  order(id: "gid://shopify/Order/3251164250287") {
    fulfillmentOrders(first: 10) {
      edges {
        node {
          id
          status
          assignedLocation {
            name
          }
          lineItems(first: 20) {
            edges {
              node {
                lineItem {
                  name
                  variant {
                    id
                  }
                }
                remainingQuantity
                totalQuantity
              }
            }
          }
        }
      }
    }
  }
}

###
# SHOPIFY create
POST https://kids-living.myshopify.com/admin/api/2021-01/graphql.json
Content-Type: application/graphql
X-Shopify-Access-Token: 7522f1ec2ce1989ac523647deae8d00b

# TODO quantities will be known from webhook - make use of it

{
  productVariant(id: "gid://shopify/ProductVariant/37528030412975") {
    id
    metafields(first: 10) {
      edges {
        node {
          id
          key
          namespace
          value
        }
      }
    }
  }
}

###
# SHOPIFY create
POST https://kids-living.myshopify.com/admin/api/2021-01/graphql.json
Content-Type: application/graphql
X-Shopify-Access-Token: 7522f1ec2ce1989ac523647deae8d00b

# TODO quantities will be known from webhook - make use of it

{
  product(id: "gid://shopify/Product/4536570904636") {
    id
    status
    productType
    descriptionHtml
    tags
    featuredImage {
      id
    }
    metafield(key: "shopify", namespace: "vend") {
      key
      value
    }
    variants(first: 32) {
      edges {
        node {
          id
          image {
            id
          }
          inventoryQuantity
          price
          sku
          selectedOptions {
            value
          }
          metafield(key: "active", namespace: "vend") {
            key
            value
          }
          inventoryItem {
            id
            inventoryLevels(first: 2) {
              edges {
                node {
                  id
                  available
                  location {
                    id
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

###
# SHOPIFY create
POST https://kids-living.myshopify.com/admin/api/2021-01/graphql.json
Content-Type: application/graphql
X-Shopify-Access-Token: 7522f1ec2ce1989ac523647deae8d00b

# TODO quantities will be known from webhook - make use of it

mutation {
  productVariantUpdate(input: {id: "gid://shopify/ProductVariant/31841950007356", metafields: [{ key: "preorders", valueType: JSON_STRING, value: "[{\"name\":\"End May container\",\"quantity\":\"24.00000\"}]", namespace: "vend"}]}) {
    product {
      id
    }
    productVariant {
      id
    }
    userErrors {
      field
      message
    }
  }
}

###
