# SHOPIFY
POST http://localhost:3000/api/2021-02/order.create
Content-Type: application/json
Accept: application/json
x-shopify-shop-domain: kids-living.myshopify.com

{
  "id": 3833396461743,
  "admin_graphql_api_id": "gid://shopify/Order/3833396461743",
  "app_id": 580111,
  "browser_ip": "102.132.229.53",
  "buyer_accepts_marketing": false,
  "cancel_reason": null,
  "cancelled_at": null,
  "cart_token": null,
  "checkout_id": 20927694471343,
  "checkout_token": "275bdf6d5767e1844f9cdbccbba58c6c",
  "client_details": {
    "accept_language": "en-GB,en;q=0.9,en-US;q=0.8",
    "browser_height": 657,
    "browser_ip": "102.132.229.53",
    "browser_width": 1349,
    "session_hash": null,
    "user_agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36 Edg/90.0.818.62"
  },
  "closed_at": null,
  "confirmed": true,
  "contact_email": "stefanialorimer@telkomsa.net",
  "created_at": "2021-05-17T09:06:36+02:00",
  "currency": "ZAR",
  "current_subtotal_price": "938.00",
  "current_subtotal_price_set": {
    "shop_money": {
      "amount": "938.00",
      "currency_code": "ZAR"
    },
    "presentment_money": {
      "amount": "938.00",
      "currency_code": "ZAR"
    }
  },
  "current_total_discounts": "0.00",
  "current_total_discounts_set": {
    "shop_money": {
      "amount": "0.00",
      "currency_code": "ZAR"
    },
    "presentment_money": {
      "amount": "0.00",
      "currency_code": "ZAR"
    }
  },
  "current_total_duties_set": null,
  "current_total_price": "1058.00",
  "current_total_price_set": {
    "shop_money": {
      "amount": "1058.00",
      "currency_code": "ZAR"
    },
    "presentment_money": {
      "amount": "1058.00",
      "currency_code": "ZAR"
    }
  },
  "current_total_tax": "122.35",
  "current_total_tax_set": {
    "shop_money": {
      "amount": "122.35",
      "currency_code": "ZAR"
    },
    "presentment_money": {
      "amount": "122.35",
      "currency_code": "ZAR"
    }
  },
  "customer_locale": "en",
  "device_id": null,
  "discount_codes": [],
  "email": "stefanialorimer@telkomsa.net",
  "financial_status": "paid",
  "fulfillment_status": "fulfilled",
  "gateway": "paygate",
  "landing_site": "/collections/feeding-high-chairs-ikea-antilop",
  "landing_site_ref": null,
  "location_id": null,
  "name": "#13567",
  "note": "",
  "note_attributes": [],
  "number": 12567,
  "order_number": 13567,
  "order_status_url": "https://kidsliving.co.za/15673213/orders/f3b402e43db2fe235685ecddf49289cb/authenticate?key=78b25456ddf4b7945232b16ecc3972a0",
  "original_total_duties_set": null,
  "payment_gateway_names": [
    "paygate"
  ],
  "phone": null,
  "presentment_currency": "ZAR",
  "processed_at": "2021-05-17T09:06:36+02:00",
  "processing_method": "offsite",
  "reference": null,
  "referring_site": "",
  "source_identifier": null,
  "source_name": "web",
  "source_url": null,
  "subtotal_price": "938.00",
  "subtotal_price_set": {
    "shop_money": {
      "amount": "938.00",
      "currency_code": "ZAR"
    },
    "presentment_money": {
      "amount": "938.00",
      "currency_code": "ZAR"
    }
  },
  "tags": "",
  "tax_lines": [
    {
      "price": "122.35",
      "rate": 0.15,
      "title": "VAT",
      "price_set": {
        "shop_money": {
          "amount": "122.35",
          "currency_code": "ZAR"
        },
        "presentment_money": {
          "amount": "122.35",
          "currency_code": "ZAR"
        }
      }
    }
  ],
  "taxes_included": true,
  "test": false,
  "token": "f3b402e43db2fe235685ecddf49289cb",
  "total_discounts": "0.00",
  "total_discounts_set": {
    "shop_money": {
      "amount": "0.00",
      "currency_code": "ZAR"
    },
    "presentment_money": {
      "amount": "0.00",
      "currency_code": "ZAR"
    }
  },
  "total_line_items_price": "938.00",
  "total_line_items_price_set": {
    "shop_money": {
      "amount": "938.00",
      "currency_code": "ZAR"
    },
    "presentment_money": {
      "amount": "938.00",
      "currency_code": "ZAR"
    }
  },
  "total_outstanding": "0.00",
  "total_price": "1058.00",
  "total_price_set": {
    "shop_money": {
      "amount": "1058.00",
      "currency_code": "ZAR"
    },
    "presentment_money": {
      "amount": "1058.00",
      "currency_code": "ZAR"
    }
  },
  "total_price_usd": "74.84",
  "total_shipping_price_set": {
    "shop_money": {
      "amount": "120.00",
      "currency_code": "ZAR"
    },
    "presentment_money": {
      "amount": "120.00",
      "currency_code": "ZAR"
    }
  },
  "total_tax": "122.35",
  "total_tax_set": {
    "shop_money": {
      "amount": "122.35",
      "currency_code": "ZAR"
    },
    "presentment_money": {
      "amount": "122.35",
      "currency_code": "ZAR"
    }
  },
  "total_tip_received": "0.00",
  "total_weight": 3400,
  "updated_at": "2021-05-17T12:33:43+02:00",
  "user_id": null,
  "billing_address": {
    "first_name": "Michele",
    "address1": "40A 12th Ave Parktown North",
    "phone": "082 442 4875",
    "city": "Johannesburg",
    "zip": "2193",
    "province": "Gauteng",
    "country": "South Africa",
    "last_name": "White",
    "address2": "",
    "company": "",
    "latitude": -26.1395094,
    "longitude": 28.0301008,
    "name": "Michele White",
    "country_code": "ZA",
    "province_code": "GT"
  },
  "customer": {
    "id": 5217676951727,
    "email": "stefanialorimer@telkomsa.net",
    "accepts_marketing": false,
    "created_at": "2021-05-17T08:55:02+02:00",
    "updated_at": "2021-05-17T09:06:37+02:00",
    "first_name": "Michele",
    "last_name": "White",
    "orders_count": 1,
    "state": "disabled",
    "total_spent": "1058.00",
    "last_order_id": 3833396461743,
    "note": null,
    "verified_email": true,
    "multipass_identifier": null,
    "tax_exempt": false,
    "phone": null,
    "tags": "",
    "last_order_name": "#13567",
    "currency": "ZAR",
    "accepts_marketing_updated_at": "2021-05-17T08:55:02+02:00",
    "marketing_opt_in_level": null,
    "tax_exemptions": [],
    "admin_graphql_api_id": "gid://shopify/Customer/5217676951727",
    "default_address": {
      "id": 6396839035055,
      "customer_id": 5217676951727,
      "first_name": "Michele",
      "last_name": "White",
      "company": "",
      "address1": "40A 12th Ave Parktown North",
      "address2": "",
      "city": "Johannesburg",
      "province": "Gauteng",
      "country": "South Africa",
      "zip": "2193",
      "phone": "082 442 4875",
      "name": "Michele White",
      "province_code": "GT",
      "country_code": "ZA",
      "country_name": "South Africa",
      "default": true
    }
  },
  "discount_applications": [],
  "fulfillments": [
    {
      "id": 3384475320495,
      "admin_graphql_api_id": "gid://shopify/Fulfillment/3384475320495",
      "created_at": "2021-05-17T12:33:43+02:00",
      "location_id": 36654383164,
      "name": "#13567.1",
      "order_id": 3833396461743,
      "receipt": {},
      "service": "manual",
      "shipment_status": null,
      "status": "success",
      "tracking_company": "Other",
      "tracking_number": "TCG29879050",
      "tracking_numbers": [
        "TCG29879050"
      ],
      "tracking_url": null,
      "tracking_urls": [],
      "updated_at": "2021-05-17T12:33:43+02:00",
      "line_items": [
        {
          "id": 9919575425199,
          "admin_graphql_api_id": "gid://shopify/LineItem/9919575425199",
          "fulfillable_quantity": 0,
          "fulfillment_service": "manual",
          "fulfillment_status": "fulfilled",
          "gift_card": false,
          "grams": 0,
          "name": "Antilop Cushion Klammig to fit Antilop high chair - Grey Yellow",
          "origin_location": {
            "id": 2030453063740,
            "country_code": "ZA",
            "province_code": "WC",
            "name": "Kids Living",
            "address1": "15 Hudson Street",
            "address2": "Greenpoint",
            "city": "Cape Town",
            "zip": "8001"
          },
          "price": "339.00",
          "price_set": {
            "shop_money": {
              "amount": "339.00",
              "currency_code": "ZAR"
            },
            "presentment_money": {
              "amount": "339.00",
              "currency_code": "ZAR"
            }
          },
          "product_exists": true,
          "product_id": 4492837617724,
          "properties": [],
          "quantity": 1,
          "requires_shipping": true,
          "sku": "14591",
          "taxable": true,
          "title": "Antilop Cushion Klammig to fit Antilop high chair",
          "total_discount": "0.00",
          "total_discount_set": {
            "shop_money": {
              "amount": "0.00",
              "currency_code": "ZAR"
            },
            "presentment_money": {
              "amount": "0.00",
              "currency_code": "ZAR"
            }
          },
          "variant_id": 31937087275068,
          "variant_inventory_management": "shopify",
          "variant_title": "Grey Yellow",
          "vendor": "Ikea",
          "tax_lines": [
            {
              "price": "44.22",
              "price_set": {
                "shop_money": {
                  "amount": "44.22",
                  "currency_code": "ZAR"
                },
                "presentment_money": {
                  "amount": "44.22",
                  "currency_code": "ZAR"
                }
              },
              "rate": 0.15,
              "title": "VAT"
            }
          ],
          "duties": [],
          "discount_allocations": []
        },
        {
          "id": 9919575457967,
          "admin_graphql_api_id": "gid://shopify/LineItem/9919575457967",
          "fulfillable_quantity": 0,
          "fulfillment_service": "manual",
          "fulfillment_status": "fulfilled",
          "gift_card": false,
          "grams": 3400,
          "name": "High Chair White Antilop with Tray",
          "origin_location": {
            "id": 2030453063740,
            "country_code": "ZA",
            "province_code": "WC",
            "name": "Kids Living",
            "address1": "15 Hudson Street",
            "address2": "Greenpoint",
            "city": "Cape Town",
            "zip": "8001"
          },
          "price": "599.00",
          "price_set": {
            "shop_money": {
              "amount": "599.00",
              "currency_code": "ZAR"
            },
            "presentment_money": {
              "amount": "599.00",
              "currency_code": "ZAR"
            }
          },
          "product_exists": true,
          "product_id": 10150274194,
          "properties": [],
          "quantity": 1,
          "requires_shipping": true,
          "sku": "FHIGHANTILOP",
          "taxable": true,
          "title": "High Chair White Antilop with Tray",
          "total_discount": "0.00",
          "total_discount_set": {
            "shop_money": {
              "amount": "0.00",
              "currency_code": "ZAR"
            },
            "presentment_money": {
              "amount": "0.00",
              "currency_code": "ZAR"
            }
          },
          "variant_id": 39537432530,
          "variant_inventory_management": "shopify",
          "variant_title": "",
          "vendor": "Ikea",
          "tax_lines": [
            {
              "price": "78.13",
              "price_set": {
                "shop_money": {
                  "amount": "78.13",
                  "currency_code": "ZAR"
                },
                "presentment_money": {
                  "amount": "78.13",
                  "currency_code": "ZAR"
                }
              },
              "rate": 0.15,
              "title": "VAT"
            }
          ],
          "duties": [],
          "discount_allocations": []
        }
      ]
    }
  ],
  "line_items": [
    {
      "id": 9919575425199,
      "admin_graphql_api_id": "gid://shopify/LineItem/9919575425199",
      "fulfillable_quantity": 0,
      "fulfillment_service": "manual",
      "fulfillment_status": "fulfilled",
      "gift_card": false,
      "grams": 0,
      "name": "Antilop Cushion Klammig to fit Antilop high chair - Grey Yellow",
      "origin_location": {
        "id": 2030453063740,
        "country_code": "ZA",
        "province_code": "WC",
        "name": "Kids Living",
        "address1": "15 Hudson Street",
        "address2": "Greenpoint",
        "city": "Cape Town",
        "zip": "8001"
      },
      "price": "339.00",
      "price_set": {
        "shop_money": {
          "amount": "339.00",
          "currency_code": "ZAR"
        },
        "presentment_money": {
          "amount": "339.00",
          "currency_code": "ZAR"
        }
      },
      "product_exists": true,
      "product_id": 4492837617724,
      "properties": [],
      "quantity": 1,
      "requires_shipping": true,
      "sku": "14591",
      "taxable": true,
      "title": "Antilop Cushion Klammig to fit Antilop high chair",
      "total_discount": "0.00",
      "total_discount_set": {
        "shop_money": {
          "amount": "0.00",
          "currency_code": "ZAR"
        },
        "presentment_money": {
          "amount": "0.00",
          "currency_code": "ZAR"
        }
      },
      "variant_id": 31937087275068,
      "variant_inventory_management": "shopify",
      "variant_title": "Grey Yellow",
      "vendor": "Ikea",
      "tax_lines": [
        {
          "price": "44.22",
          "price_set": {
            "shop_money": {
              "amount": "44.22",
              "currency_code": "ZAR"
            },
            "presentment_money": {
              "amount": "44.22",
              "currency_code": "ZAR"
            }
          },
          "rate": 0.15,
          "title": "VAT"
        }
      ],
      "duties": [],
      "discount_allocations": []
    },
    {
      "id": 9919575457967,
      "admin_graphql_api_id": "gid://shopify/LineItem/9919575457967",
      "fulfillable_quantity": 0,
      "fulfillment_service": "manual",
      "fulfillment_status": "fulfilled",
      "gift_card": false,
      "grams": 3400,
      "name": "High Chair White Antilop with Tray",
      "origin_location": {
        "id": 2030453063740,
        "country_code": "ZA",
        "province_code": "WC",
        "name": "Kids Living",
        "address1": "15 Hudson Street",
        "address2": "Greenpoint",
        "city": "Cape Town",
        "zip": "8001"
      },
      "price": "599.00",
      "price_set": {
        "shop_money": {
          "amount": "599.00",
          "currency_code": "ZAR"
        },
        "presentment_money": {
          "amount": "599.00",
          "currency_code": "ZAR"
        }
      },
      "product_exists": true,
      "product_id": 10150274194,
      "properties": [],
      "quantity": 1,
      "requires_shipping": true,
      "sku": "FHIGHANTILOP",
      "taxable": true,
      "title": "High Chair White Antilop with Tray",
      "total_discount": "0.00",
      "total_discount_set": {
        "shop_money": {
          "amount": "0.00",
          "currency_code": "ZAR"
        },
        "presentment_money": {
          "amount": "0.00",
          "currency_code": "ZAR"
        }
      },
      "variant_id": 39537432530,
      "variant_inventory_management": "shopify",
      "variant_title": "",
      "vendor": "Ikea",
      "tax_lines": [
        {
          "price": "78.13",
          "price_set": {
            "shop_money": {
              "amount": "78.13",
              "currency_code": "ZAR"
            },
            "presentment_money": {
              "amount": "78.13",
              "currency_code": "ZAR"
            }
          },
          "rate": 0.15,
          "title": "VAT"
        }
      ],
      "duties": [],
      "discount_allocations": []
    }
  ],
  "refunds": [],
  "shipping_address": {
    "first_name": "Michele",
    "address1": "40A 12th Ave Parktown North",
    "phone": "082 442 4875",
    "city": "Johannesburg",
    "zip": "2193",
    "province": "Gauteng",
    "country": "South Africa",
    "last_name": "White",
    "address2": "",
    "company": "",
    "latitude": -26.1395094,
    "longitude": 28.0301008,
    "name": "Michele White",
    "country_code": "ZA",
    "province_code": "GT"
  },
  "shipping_lines": [
    {
      "id": 3225604227247,
      "carrier_identifier": "414127336c64f5eed2fa6b34fbc5a7e3",
      "code": "courier-door-to-door-delivery-economy",
      "delivery_category": null,
      "discounted_price": "120.00",
      "discounted_price_set": {
        "shop_money": {
          "amount": "120.00",
          "currency_code": "ZAR"
        },
        "presentment_money": {
          "amount": "120.00",
          "currency_code": "ZAR"
        }
      },
      "phone": null,
      "price": "120.00",
      "price_set": {
        "shop_money": {
          "amount": "120.00",
          "currency_code": "ZAR"
        },
        "presentment_money": {
          "amount": "120.00",
          "currency_code": "ZAR"
        }
      },
      "requested_fulfillment_service_id": null,
      "source": "uAfrica Shipping Rates",
      "title": "Courier Door to Door Delivery - Economy",
      "tax_lines": [],
      "discount_allocations": []
    }
  ]
}


###
# SHOPIFY create
POST https://kids-living.myshopify.com/admin/api/2021-01/graphql.json
Content-Type: application/graphql
X-Shopify-Access-Token: 7522f1ec2ce1989ac523647deae8d00b

# TODO quantities will be known from webhook - make use of it

{
  order(id: "gid://shopify/Order/3251164250287") {
    fulfillmentOrders(first: 10) {
      edges {
        node {
          id
          status
          assignedLocation {
            name
          }
          lineItems(first: 20) {
            edges {
              node {
                lineItem {
                  name
                  variant {
                    id
                  }
                }
                remainingQuantity
                totalQuantity
              }
            }
          }
        }
      }
    }
  }
}

###
# SHOPIFY create
POST https://kids-living.myshopify.com/admin/api/2021-01/graphql.json
Content-Type: application/graphql
X-Shopify-Access-Token: 7522f1ec2ce1989ac523647deae8d00b

# TODO quantities will be known from webhook - make use of it

{
  productVariant(id: "gid://shopify/ProductVariant/37528030412975") {
    id
    metafields(first: 10) {
      edges {
        node {
          id
          key
          namespace
          value
        }
      }
    }
  }
}

###
# SHOPIFY create
POST https://kids-living.myshopify.com/admin/api/2021-01/graphql.json
Content-Type: application/graphql
X-Shopify-Access-Token: 7522f1ec2ce1989ac523647deae8d00b

# TODO quantities will be known from webhook - make use of it

{
  product(id: "gid://shopify/Product/4536570904636") {
    id
    status
    productType
    descriptionHtml
    tags
    featuredImage {
      id
    }
    metafield(key: "shopify", namespace: "vend") {
      key
      value
    }
    variants(first: 32) {
      edges {
        node {
          id
          image {
            id
          }
          inventoryQuantity
          price
          sku
          selectedOptions {
            value
          }
          metafield(key: "active", namespace: "vend") {
            key
            value
          }
          inventoryItem {
            id
            inventoryLevels(first: 2) {
              edges {
                node {
                  id
                  available
                  location {
                    id
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

###
# SHOPIFY create
POST https://kids-living.myshopify.com/admin/api/2021-01/graphql.json
Content-Type: application/graphql
X-Shopify-Access-Token: 7522f1ec2ce1989ac523647deae8d00b

# TODO quantities will be known from webhook - make use of it

mutation {
  productVariantUpdate(input: {id: "gid://shopify/ProductVariant/31841950007356", metafields: [{ key: "preorders", valueType: JSON_STRING, value: "[{\"name\":\"End May container\",\"quantity\":\"24.00000\"}]", namespace: "vend"}]}) {
    product {
      id
    }
    productVariant {
      id
    }
    userErrors {
      field
      message
    }
  }
}

###
