# SHOPIFY
POST http://localhost:3000/api/2021-02/order.create
Content-Type: application/json
Accept: application/json
x-shopify-shop-domain: kids-living.myshopify.com

{
  "id": 3257938804911,
  "email": "felix@tellmann.co.za",
  "closed_at": null,
  "created_at": "2021-02-20T12:53:08+02:00",
  "updated_at": "2021-02-20T12:53:10+02:00",
  "number": 11455,
  "note": "",
  "token": "7c8042eea2e25c3a0296d7ec7783fd29",
  "gateway": null,
  "test": false,
  "total_price": "0.00",
  "subtotal_price": "0.00",
  "total_weight": 0,
  "total_tax": "0.00",
  "taxes_included": true,
  "currency": "ZAR",
  "financial_status": "paid",
  "confirmed": true,
  "total_discounts": "2.00",
  "total_line_items_price": "2.00",
  "cart_token": "847d717eee7be366243ade01d11b0325",
  "buyer_accepts_marketing": true,
  "name": "#12455",
  "referring_site": "",
  "landing_site": "/",
  "cancelled_at": null,
  "cancel_reason": null,
  "total_price_usd": "0.00",
  "checkout_token": "7a67acd81ed879b5e4e863dd8c578553",
  "reference": null,
  "user_id": null,
  "location_id": null,
  "source_identifier": null,
  "source_url": null,
  "processed_at": "2021-02-20T12:53:08+02:00",
  "device_id": null,
  "phone": null,
  "customer_locale": "en",
  "app_id": 580111,
  "browser_ip": "102.132.251.94",
  "client_details": {
    "accept_language": "en-GB,en;q=0.9,en-US;q=0.8,en-ZA;q=0.7",
    "browser_height": 977,
    "browser_ip": "102.132.251.94",
    "browser_width": 1903,
    "session_hash": null,
    "user_agent": "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4423.0 Safari/537.36"
  },
  "landing_site_ref": null,
  "order_number": 12455,
  "discount_applications": [
    {
      "type": "discount_code",
      "value": "100.0",
      "value_type": "percentage",
      "allocation_method": "across",
      "target_selection": "all",
      "target_type": "line_item",
      "code": "TESTTESTTEST"
    }
  ],
  "discount_codes": [
    {
      "code": "TESTTESTTEST",
      "amount": "2.00",
      "type": "percentage"
    }
  ],
  "note_attributes": [],
  "payment_gateway_names": [],
  "processing_method": "free",
  "checkout_id": 18849419853999,
  "source_name": "web",
  "fulfillment_status": null,
  "tax_lines": [],
  "tags": "",
  "contact_email": "felix@tellmann.co.za",
  "order_status_url": "https://kidsliving.co.za/15673213/orders/7c8042eea2e25c3a0296d7ec7783fd29/authenticate?key=eeba18140a0e73b71ce5a4be3540c625",
  "presentment_currency": "ZAR",
  "total_line_items_price_set": {
    "shop_money": {
      "amount": "2.00",
      "currency_code": "ZAR"
    },
    "presentment_money": {
      "amount": "2.00",
      "currency_code": "ZAR"
    }
  },
  "total_discounts_set": {
    "shop_money": {
      "amount": "2.00",
      "currency_code": "ZAR"
    },
    "presentment_money": {
      "amount": "2.00",
      "currency_code": "ZAR"
    }
  },
  "total_shipping_price_set": {
    "shop_money": {
      "amount": "0.00",
      "currency_code": "ZAR"
    },
    "presentment_money": {
      "amount": "0.00",
      "currency_code": "ZAR"
    }
  },
  "subtotal_price_set": {
    "shop_money": {
      "amount": "0.00",
      "currency_code": "ZAR"
    },
    "presentment_money": {
      "amount": "0.00",
      "currency_code": "ZAR"
    }
  },
  "total_price_set": {
    "shop_money": {
      "amount": "0.00",
      "currency_code": "ZAR"
    },
    "presentment_money": {
      "amount": "0.00",
      "currency_code": "ZAR"
    }
  },
  "total_tax_set": {
    "shop_money": {
      "amount": "0.00",
      "currency_code": "ZAR"
    },
    "presentment_money": {
      "amount": "0.00",
      "currency_code": "ZAR"
    }
  },
  "line_items": [
    {
      "id": 9228283117743,
      "variant_id": 38312911372463,
      "title": "TESTING TESTING - DO NOT FULFILL",
      "quantity": 1,
      "sku": "20502",
      "variant_title": "fancy",
      "vendor": "Kids Living",
      "fulfillment_service": "manual",
      "product_id": 4536570904636,
      "requires_shipping": true,
      "taxable": false,
      "gift_card": false,
      "name": "TESTING TESTING - DO NOT FULFILL - fancy",
      "variant_inventory_management": "shopify",
      "properties": [],
      "product_exists": true,
      "fulfillable_quantity": 1,
      "grams": 0,
      "price": "1.00",
      "total_discount": "0.00",
      "fulfillment_status": null,
      "price_set": {
        "shop_money": {
          "amount": "1.00",
          "currency_code": "ZAR"
        },
        "presentment_money": {
          "amount": "1.00",
          "currency_code": "ZAR"
        }
      },
      "total_discount_set": {
        "shop_money": {
          "amount": "0.00",
          "currency_code": "ZAR"
        },
        "presentment_money": {
          "amount": "0.00",
          "currency_code": "ZAR"
        }
      },
      "discount_allocations": [
        {
          "amount": "1.00",
          "discount_application_index": 0,
          "amount_set": {
            "shop_money": {
              "amount": "1.00",
              "currency_code": "ZAR"
            },
            "presentment_money": {
              "amount": "1.00",
              "currency_code": "ZAR"
            }
          }
        }
      ],
      "duties": [],
      "admin_graphql_api_id": "gid://shopify/LineItem/9228283117743",
      "tax_lines": [
        {
          "title": "VAT",
          "price": "0.00",
          "rate": 0.15,
          "price_set": {
            "shop_money": {
              "amount": "0.00",
              "currency_code": "ZAR"
            },
            "presentment_money": {
              "amount": "0.00",
              "currency_code": "ZAR"
            }
          }
        }
      ],
      "origin_location": {
        "id": 2030453063740,
        "country_code": "ZA",
        "province_code": "WC",
        "name": "Kids Living",
        "address1": "15 Hudson Street",
        "address2": "Greenpoint",
        "city": "Cape Town",
        "zip": "8001"
      }
    },
    {
      "id": 9228283150511,
      "variant_id": 38312872968367,
      "title": "TESTING TESTING - DO NOT FULFILL",
      "quantity": 1,
      "sku": "TESTINGTESTINGDefaultTitle",
      "variant_title": "cool",
      "vendor": "Kids Living",
      "fulfillment_service": "manual",
      "product_id": 4536570904636,
      "requires_shipping": true,
      "taxable": false,
      "gift_card": false,
      "name": "TESTING TESTING - DO NOT FULFILL - cool",
      "variant_inventory_management": "shopify",
      "properties": [],
      "product_exists": true,
      "fulfillable_quantity": 1,
      "grams": 0,
      "price": "1.00",
      "total_discount": "0.00",
      "fulfillment_status": null,
      "price_set": {
        "shop_money": {
          "amount": "1.00",
          "currency_code": "ZAR"
        },
        "presentment_money": {
          "amount": "1.00",
          "currency_code": "ZAR"
        }
      },
      "total_discount_set": {
        "shop_money": {
          "amount": "0.00",
          "currency_code": "ZAR"
        },
        "presentment_money": {
          "amount": "0.00",
          "currency_code": "ZAR"
        }
      },
      "discount_allocations": [
        {
          "amount": "1.00",
          "discount_application_index": 0,
          "amount_set": {
            "shop_money": {
              "amount": "1.00",
              "currency_code": "ZAR"
            },
            "presentment_money": {
              "amount": "1.00",
              "currency_code": "ZAR"
            }
          }
        }
      ],
      "duties": [],
      "admin_graphql_api_id": "gid://shopify/LineItem/9228283150511",
      "tax_lines": [
        {
          "title": "VAT",
          "price": "0.00",
          "rate": 0.15,
          "price_set": {
            "shop_money": {
              "amount": "0.00",
              "currency_code": "ZAR"
            },
            "presentment_money": {
              "amount": "0.00",
              "currency_code": "ZAR"
            }
          }
        }
      ],
      "origin_location": {
        "id": 2030453063740,
        "country_code": "ZA",
        "province_code": "WC",
        "name": "Kids Living",
        "address1": "15 Hudson Street",
        "address2": "Greenpoint",
        "city": "Cape Town",
        "zip": "8001"
      }
    }
  ],
  "fulfillments": [],
  "refunds": [],
  "total_tip_received": "0.0",
  "original_total_duties_set": null,
  "current_total_duties_set": null,
  "admin_graphql_api_id": "gid://shopify/Order/3257938804911",
  "shipping_lines": [
    {
      "id": 2688476676271,
      "title": "Collect from Johannesburg - Sandton Store",
      "price": "0.00",
      "code": "Collect from Johannesburg - Sandton Store",
      "source": "shopify",
      "phone": null,
      "requested_fulfillment_service_id": null,
      "delivery_category": null,
      "carrier_identifier": null,
      "discounted_price": "0.00",
      "price_set": {
        "shop_money": {
          "amount": "0.00",
          "currency_code": "ZAR"
        },
        "presentment_money": {
          "amount": "0.00",
          "currency_code": "ZAR"
        }
      },
      "discounted_price_set": {
        "shop_money": {
          "amount": "0.00",
          "currency_code": "ZAR"
        },
        "presentment_money": {
          "amount": "0.00",
          "currency_code": "ZAR"
        }
      },
      "discount_allocations": [],
      "tax_lines": []
    }
  ],
  "billing_address": {
    "first_name": "Felix",
    "address1": "Unit 3, Adelphi",
    "phone": "076 031 3590",
    "city": "Cape Town",
    "zip": "8001",
    "province": "Western Cape",
    "country": "South Africa",
    "last_name": "Tellmann",
    "address2": "21 Bellair Road",
    "company": "",
    "latitude": -33.9211185,
    "longitude": 18.4216702,
    "name": "Felix Tellmann",
    "country_code": "ZA",
    "province_code": "WC"
  },
  "shipping_address": {
    "first_name": "Felix",
    "address1": "Unit 3, Adelphi",
    "phone": "076 031 3590",
    "city": "Cape Town",
    "zip": "8001",
    "province": "Western Cape",
    "country": "South Africa",
    "last_name": "Tellmann",
    "address2": "21 Bellair Road",
    "company": "",
    "latitude": -33.9211185,
    "longitude": 18.4216702,
    "name": "Felix Tellmann",
    "country_code": "ZA",
    "province_code": "WC"
  },
  "customer": {
    "id": 5435238354,
    "email": "felix@tellmann.co.za",
    "accepts_marketing": true,
    "created_at": "2017-05-25T20:32:08+02:00",
    "updated_at": "2021-02-22T11:53:57+02:00",
    "first_name": "Felix",
    "last_name": "Tellmann",
    "orders_count": 59,
    "state": "enabled",
    "total_spent": "6.00",
    "last_order_id": 3261141319855,
    "note": null,
    "verified_email": false,
    "multipass_identifier": null,
    "tax_exempt": false,
    "phone": null,
    "tags": "newsletter, subscribed",
    "last_order_name": "#12481",
    "currency": "ZAR",
    "accepts_marketing_updated_at": "2018-12-29T22:19:46+02:00",
    "marketing_opt_in_level": "single_opt_in",
    "tax_exemptions": [],
    "admin_graphql_api_id": "gid://shopify/Customer/5435238354",
    "default_address": {
      "id": 5656513708207,
      "customer_id": 5435238354,
      "first_name": "Felix",
      "last_name": "Tellmann",
      "company": "",
      "address1": "Unit 3, Adelphi",
      "address2": "21 Bellair Road",
      "city": "Cape Town",
      "province": "Western Cape",
      "country": "South Africa",
      "zip": "8001",
      "phone": "0760313590",
      "name": "Felix Tellmann",
      "province_code": "WC",
      "country_code": "ZA",
      "country_name": "South Africa",
      "default": true
    }
  }
}


###
# SHOPIFY create
POST https://kids-living.myshopify.com/admin/api/2021-01/graphql.json
Content-Type: application/graphql
X-Shopify-Access-Token: 7522f1ec2ce1989ac523647deae8d00b

# TODO quantities will be known from webhook - make use of it

{
  order(id: "gid://shopify/Order/3251164250287") {
    fulfillmentOrders(first: 10) {
      edges {
        node {
          id
          status
          assignedLocation {
            name
          }
          lineItems(first: 20) {
            edges {
              node {
                lineItem {
                  name
                  variant {
                    id
                  }
                }
                remainingQuantity
                totalQuantity
              }
            }
          }
        }
      }
    }
  }
}

###
# SHOPIFY create
POST https://kids-living.myshopify.com/admin/api/2021-01/graphql.json
Content-Type: application/graphql
X-Shopify-Access-Token: 7522f1ec2ce1989ac523647deae8d00b

# TODO quantities will be known from webhook - make use of it

{
  productVariant(id: "gid://shopify/ProductVariant/38312911372463") {
    id
    metafields(first: 10) {
      edges {
        node {
          id
          key
          namespace
          value
        }
      }
    }
  }
}

###
# SHOPIFY create
POST https://kids-living.myshopify.com/admin/api/2021-01/graphql.json
Content-Type: application/graphql
X-Shopify-Access-Token: 7522f1ec2ce1989ac523647deae8d00b

# TODO quantities will be known from webhook - make use of it

{
  product(id: "gid://shopify/Product/4536570904636") {
    id
    status
    productType
    descriptionHtml
    tags
    featuredImage {
      id
    }
    metafield(key: "shopify", namespace: "vend") {
      key
      value
    }
    variants(first: 32) {
      edges {
        node {
          id
          image {
            id
          }
          inventoryQuantity
          price
          sku
          selectedOptions {
            value
          }
          metafield(key: "active", namespace: "vend") {
            key
            value
          }
          inventoryItem {
            id
            inventoryLevels(first: 2) {
              edges {
                node {
                  id
                  available
                  location {
                    id
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

###
# SHOPIFY create
POST https://kids-living.myshopify.com/admin/api/2021-01/graphql.json
Content-Type: application/graphql
X-Shopify-Access-Token: 7522f1ec2ce1989ac523647deae8d00b

# TODO quantities will be known from webhook - make use of it

mutation {
  productVariantUpdate(input: {id: "gid://shopify/ProductVariant/38312911372463", metafields: [{ key: "active", valueType: STRING, value: "false", namespace: "vend"}]}) {
    product {
      id
    }
    productVariant {
      id
    }
    userErrors {
      field
      message
    }
  }
}

###
