# VEND
POST http://localhost:3000/api/2021-02/product.update
Content-Type: application/json
Accept: application/json

{
  "retailer_id": "02dcd191-ae2b-11e6-f485-4cb686805cbf",
  "payload": "{\"handle\":\"testing-testing-do-not-fulfill\",\"source_id\":\"4536570904636\",\"source\":\"SHOPIFY\"}"
}
###
# VEND
POST http://localhost:3000/api/2021-02/product.update
Content-Type: application/json
Accept: application/json

{
  "retailer_id": "02dcd191-ae2b-11e6-f485-4cb686805cbf",
  "payload": "{\"handle\":\"CottonballLights\",\"source_id\":\"6246512853167\",\"source\":\"SHOPIFY\"}"
}
###
# VEND via WEBSITE
POST https://kidsliving-api.vercel.app /api/2021-02/product.update
Content-Type: application/json
Accept: application/json

{
  "retailer_id": "02dcd191-ae2b-11e6-f485-4cb686805cbf",
  "payload": "{\"handle\":\"testing-testing-do-not-fulfill\",\"source_id\":\"4536570904636\",\"source\":\"SHOPIFY\"}"
}

#### VEND
POST http://localhost:3000/api/2021-02/product.update
Content-Type: application/json
Accept: application/json

{
  "retailer_id": "02dcd191-ae2b-11e6-f485-4cb686805cbf",
  "payload": "{\"handle\":\"miffyplaymatwithbow\",\"source_id\":\"2540522471484\",\"source\":\"SHOPIFY\"}"
}

#### VEND
POST http://localhost:3000/api/2021-02/product.update
Content-Type: application/json
Accept: application/json

{
  "retailer_id": "02dcd191-ae2b-11e6-f485-4cb686805cbf",
  "payload": "{\"handle\":\"SproutStorageBin\",\"source_id\":\"10167360658\",\"source\":\"SHOPIFY\"}"
}

###

# SHOPIFY
POST http://localhost:3000/api/2021-02/product.update
Content-Type: application/json
Accept: application/json
x-shopify-shop-domain: kids-living.myshopify.com

{
  "id": 6109515153583,
  "handle": "rolltopbackpackcinnamon"
}

###

# SHOPIFY
POST https://kids-living.myshopify.com/admin/api/2021-01/graphql.json
Content-Type: application/graphql
X-Shopify-Access-Token: 7522f1ec2ce1989ac523647deae8d00b

{
    product(id: "gid://shopify/Product/9822851538") {
      title
      description
      tags
      variants(first: 32) {
        edges {
          node {
            id
            image {
              id
            }
            inventoryQuantity
            price
            sku
            selectedOptions {


                    value

            }
            inventoryItem {
              id
              inventoryLevels(first: 2) {
                edges {
                  node {
                    id
                    location {
                      id
                      name
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
###

# SHOPIFY create
POST https://kids-living.myshopify.com/admin/api/2021-01/graphql.json
Content-Type: application/graphql
X-Shopify-Access-Token: 7522f1ec2ce1989ac523647deae8d00b

mutation {
    inventoryDeactivate(inventoryLevelId: "gid://shopify/InventoryLevel/70523519036?inventory_item_id=39992756895919") {
      userErrors {
        field
        message
      }
    }
  }